[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
    "debugpy>=1.8.14,<2",
    "isort>=6.0.1,<7",
    "pre-commit>=4.2.0,<5",
    "uvicorn",
    "pytest>=8.4.1,<9",
    "pytest-asyncio>=1.4.0,<2",
    "pytest-mock",
    "pytest-xdist",
    "requests",
    "httpx",
    "ruff>=0.12.3,<0.17",
]

[project]
name = "fastapi-relax"
version = "0.2.4"
description = "A request rate limiter for fastapi"
authors = [
    { name = "long2ice", email = "long2ice@gmail.com" },
    { name = "mattcoulter7", email = "mattcoul7@gmail.com" }
]
requires-python = ">=3.12,<4"
readme = "README.md"
license = "Apache-2.0"
keywords = ["fastapi", "limiter"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "fastapi",
    "pyrate-limiter>=3.9.0",
]

[project.urls]
Homepage = "https://github.com/mattcoulter7/fastapi-relax"
Repository = "https://github.com/mattcoulter7/fastapi-relax.git"
Documentation = "https://github.com/mattcoulter7/fastapi-relax"

[tool.hatch.build.targets.sdist]
include = ["src/fastapi_relax"]

[tool.hatch.build.targets.wheel]
packages = ["src/fastapi_relax"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
